export const admin_route = '/admin'
export const login_route = '/login'
export const register_route = '/registration'
export const shop_route = '/'
export const product_route = '/product'
export const basket_route = '/basket'